SELECT
MBI_USER_NO,
COUNT(*) AS totalCount,
SUM(CASE WHEN MBI_STATUS IN ('00','01') THEN 1 ELSE 0 END) AS entering,
SUM(CASE WHEN MBI_STATUS = '11' THEN 1 ELSE 0 END) AS examine,
SUM(CASE WHEN MBI_STATUS = '20' THEN 1 ELSE 0 END) AS normal,
SUM(CASE WHEN MBI_STATUS = '21' THEN 1 ELSE 0 END) AS toBeSigned,
SUM(CASE WHEN MRI_REBUT_BATCH_NO IS NOT NULL THEN 1 ELSE 0 END) AS reject,
MBI_CREATE_TIME,
MRI_REBUT_TIME
FROM merchant_baseinfo LEFT JOIN merchant_rebutinfo ON MBI_MERCHANT_NO = MRI_MERCHANT_NO
GROUP BY MBI_USER_NO
